// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwxqpxyfxqhwlqzniyyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3eHFweHlmeHFod2xxem5peXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMTgwMDEsImV4cCI6MjA3MzY5NDAwMX0.qr30ISF5I_TxJb2GwuQ-Nt8MaoLxnPzMzA8M8g-l4_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});